name: CI
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --legacy-peer-deps